// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: atlas/web/v1/ui.proto

package uiv1

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UIServiceName is the fully-qualified name of the UIService service.
	UIServiceName = "atlas.web.v1.UIService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UIServiceViewsProcedure is the fully-qualified name of the UIService's Views RPC.
	UIServiceViewsProcedure = "/atlas.web.v1.UIService/Views"
	// UIServiceRunProcedure is the fully-qualified name of the UIService's Run RPC.
	UIServiceRunProcedure = "/atlas.web.v1.UIService/Run"
	// UIServiceAnswerProcedure is the fully-qualified name of the UIService's Answer RPC.
	UIServiceAnswerProcedure = "/atlas.web.v1.UIService/Answer"
	// UIServiceAcknowledgeProcedure is the fully-qualified name of the UIService's Acknowledge RPC.
	UIServiceAcknowledgeProcedure = "/atlas.web.v1.UIService/Acknowledge"
	// UIServiceDocumentProcedure is the fully-qualified name of the UIService's Document RPC.
	UIServiceDocumentProcedure = "/atlas.web.v1.UIService/Document"
)

// UIServiceClient is a client for the atlas.web.v1.UIService service.
type UIServiceClient interface {
	Views(context.Context, *connect.Request[ViewsRequest]) (*connect.Response[ViewsResponse], error)
	Run(context.Context, *connect.Request[RunRequest]) (*connect.ServerStreamForClient[RunResponse], error)
	Answer(context.Context, *connect.Request[AnswerRequest]) (*connect.Response[AnswerResponse], error)
	Acknowledge(context.Context, *connect.Request[AcknowledgeRequest]) (*connect.Response[AcknowledgeResponse], error)
	Document(context.Context, *connect.Request[DocumentRequest]) (*connect.Response[DocumentResponse], error)
}

// NewUIServiceClient constructs a client for the atlas.web.v1.UIService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUIServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UIServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	uIServiceMethods := File_atlas_web_v1_ui_proto.Services().ByName("UIService").Methods()
	return &uIServiceClient{
		views: connect.NewClient[ViewsRequest, ViewsResponse](
			httpClient,
			baseURL+UIServiceViewsProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Views")),
			connect.WithClientOptions(opts...),
		),
		run: connect.NewClient[RunRequest, RunResponse](
			httpClient,
			baseURL+UIServiceRunProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Run")),
			connect.WithClientOptions(opts...),
		),
		answer: connect.NewClient[AnswerRequest, AnswerResponse](
			httpClient,
			baseURL+UIServiceAnswerProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Answer")),
			connect.WithClientOptions(opts...),
		),
		acknowledge: connect.NewClient[AcknowledgeRequest, AcknowledgeResponse](
			httpClient,
			baseURL+UIServiceAcknowledgeProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Acknowledge")),
			connect.WithClientOptions(opts...),
		),
		document: connect.NewClient[DocumentRequest, DocumentResponse](
			httpClient,
			baseURL+UIServiceDocumentProcedure,
			connect.WithSchema(uIServiceMethods.ByName("Document")),
			connect.WithClientOptions(opts...),
		),
	}
}

// uIServiceClient implements UIServiceClient.
type uIServiceClient struct {
	views       *connect.Client[ViewsRequest, ViewsResponse]
	run         *connect.Client[RunRequest, RunResponse]
	answer      *connect.Client[AnswerRequest, AnswerResponse]
	acknowledge *connect.Client[AcknowledgeRequest, AcknowledgeResponse]
	document    *connect.Client[DocumentRequest, DocumentResponse]
}

// Views calls atlas.web.v1.UIService.Views.
func (c *uIServiceClient) Views(ctx context.Context, req *connect.Request[ViewsRequest]) (*connect.Response[ViewsResponse], error) {
	return c.views.CallUnary(ctx, req)
}

// Run calls atlas.web.v1.UIService.Run.
func (c *uIServiceClient) Run(ctx context.Context, req *connect.Request[RunRequest]) (*connect.ServerStreamForClient[RunResponse], error) {
	return c.run.CallServerStream(ctx, req)
}

// Answer calls atlas.web.v1.UIService.Answer.
func (c *uIServiceClient) Answer(ctx context.Context, req *connect.Request[AnswerRequest]) (*connect.Response[AnswerResponse], error) {
	return c.answer.CallUnary(ctx, req)
}

// Acknowledge calls atlas.web.v1.UIService.Acknowledge.
func (c *uIServiceClient) Acknowledge(ctx context.Context, req *connect.Request[AcknowledgeRequest]) (*connect.Response[AcknowledgeResponse], error) {
	return c.acknowledge.CallUnary(ctx, req)
}

// Document calls atlas.web.v1.UIService.Document.
func (c *uIServiceClient) Document(ctx context.Context, req *connect.Request[DocumentRequest]) (*connect.Response[DocumentResponse], error) {
	return c.document.CallUnary(ctx, req)
}

// UIServiceHandler is an implementation of the atlas.web.v1.UIService service.
type UIServiceHandler interface {
	Views(context.Context, *connect.Request[ViewsRequest]) (*connect.Response[ViewsResponse], error)
	Run(context.Context, *connect.Request[RunRequest], *connect.ServerStream[RunResponse]) error
	Answer(context.Context, *connect.Request[AnswerRequest]) (*connect.Response[AnswerResponse], error)
	Acknowledge(context.Context, *connect.Request[AcknowledgeRequest]) (*connect.Response[AcknowledgeResponse], error)
	Document(context.Context, *connect.Request[DocumentRequest]) (*connect.Response[DocumentResponse], error)
}

// NewUIServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUIServiceHandler(svc UIServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	uIServiceMethods := File_atlas_web_v1_ui_proto.Services().ByName("UIService").Methods()
	uIServiceViewsHandler := connect.NewUnaryHandler(
		UIServiceViewsProcedure,
		svc.Views,
		connect.WithSchema(uIServiceMethods.ByName("Views")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceRunHandler := connect.NewServerStreamHandler(
		UIServiceRunProcedure,
		svc.Run,
		connect.WithSchema(uIServiceMethods.ByName("Run")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceAnswerHandler := connect.NewUnaryHandler(
		UIServiceAnswerProcedure,
		svc.Answer,
		connect.WithSchema(uIServiceMethods.ByName("Answer")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceAcknowledgeHandler := connect.NewUnaryHandler(
		UIServiceAcknowledgeProcedure,
		svc.Acknowledge,
		connect.WithSchema(uIServiceMethods.ByName("Acknowledge")),
		connect.WithHandlerOptions(opts...),
	)
	uIServiceDocumentHandler := connect.NewUnaryHandler(
		UIServiceDocumentProcedure,
		svc.Document,
		connect.WithSchema(uIServiceMethods.ByName("Document")),
		connect.WithHandlerOptions(opts...),
	)
	return "/atlas.web.v1.UIService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UIServiceViewsProcedure:
			uIServiceViewsHandler.ServeHTTP(w, r)
		case UIServiceRunProcedure:
			uIServiceRunHandler.ServeHTTP(w, r)
		case UIServiceAnswerProcedure:
			uIServiceAnswerHandler.ServeHTTP(w, r)
		case UIServiceAcknowledgeProcedure:
			uIServiceAcknowledgeHandler.ServeHTTP(w, r)
		case UIServiceDocumentProcedure:
			uIServiceDocumentHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUIServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUIServiceHandler struct{}

func (UnimplementedUIServiceHandler) Views(context.Context, *connect.Request[ViewsRequest]) (*connect.Response[ViewsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atlas.web.v1.UIService.Views is not implemented"))
}

func (UnimplementedUIServiceHandler) Run(context.Context, *connect.Request[RunRequest], *connect.ServerStream[RunResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("atlas.web.v1.UIService.Run is not implemented"))
}

func (UnimplementedUIServiceHandler) Answer(context.Context, *connect.Request[AnswerRequest]) (*connect.Response[AnswerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atlas.web.v1.UIService.Answer is not implemented"))
}

func (UnimplementedUIServiceHandler) Acknowledge(context.Context, *connect.Request[AcknowledgeRequest]) (*connect.Response[AcknowledgeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atlas.web.v1.UIService.Acknowledge is not implemented"))
}

func (UnimplementedUIServiceHandler) Document(context.Context, *connect.Request[DocumentRequest]) (*connect.Response[DocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("atlas.web.v1.UIService.Document is not implemented"))
}
