// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: atlas/web/v1/ui.proto

package uiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewsRequest) Reset() {
	*x = ViewsRequest{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewsRequest) ProtoMessage() {}

func (x *ViewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewsRequest.ProtoReflect.Descriptor instead.
func (*ViewsRequest) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{0}
}

type ViewsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The loaded view files as JSON, in the shape the UI renders. Their
	// widgets are pack data, so they are not modelled field by field here.
	ViewsJson string      `protobuf:"bytes,1,opt,name=views_json,json=viewsJson,proto3" json:"views_json,omitempty"`
	Egress    []*Endpoint `protobuf:"bytes,2,rep,name=egress,proto3" json:"egress,omitempty"`
	// Whether downloads from the files root are available.
	FilesEnabled  bool `protobuf:"varint,3,opt,name=files_enabled,json=filesEnabled,proto3" json:"files_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewsResponse) Reset() {
	*x = ViewsResponse{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewsResponse) ProtoMessage() {}

func (x *ViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewsResponse.ProtoReflect.Descriptor instead.
func (*ViewsResponse) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{1}
}

func (x *ViewsResponse) GetViewsJson() string {
	if x != nil {
		return x.ViewsJson
	}
	return ""
}

func (x *ViewsResponse) GetEgress() []*Endpoint {
	if x != nil {
		return x.Egress
	}
	return nil
}

func (x *ViewsResponse) GetFilesEnabled() bool {
	if x != nil {
		return x.FilesEnabled
	}
	return false
}

type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Hosted        bool                   `protobuf:"varint,2,opt,name=hosted,proto3" json:"hosted,omitempty"`
	Tools         []string               `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	Acknowledged  bool                   `protobuf:"varint,4,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{2}
}

func (x *Endpoint) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Endpoint) GetHosted() bool {
	if x != nil {
		return x.Hosted
	}
	return false
}

func (x *Endpoint) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Endpoint) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type RunRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	View   string                 `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	Screen string                 `protobuf:"bytes,2,opt,name=screen,proto3" json:"screen,omitempty"`
	// Index into the screen's actions; -1 runs the screen itself.
	Action        int32             `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Inputs        map[string]string `protobuf:"bytes,5,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{3}
}

func (x *RunRequest) GetView() string {
	if x != nil {
		return x.View
	}
	return ""
}

func (x *RunRequest) GetScreen() string {
	if x != nil {
		return x.Screen
	}
	return ""
}

func (x *RunRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *RunRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *RunRequest) GetInputs() map[string]string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type RunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*RunResponse_Queued
	//	*RunResponse_Step
	//	*RunResponse_Ask
	//	*RunResponse_Done
	//	*RunResponse_NeedsAcknowledgement
	Event         isRunResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{4}
}

func (x *RunResponse) GetEvent() isRunResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RunResponse) GetQueued() *Queued {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_Queued); ok {
			return x.Queued
		}
	}
	return nil
}

func (x *RunResponse) GetStep() *Step {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_Step); ok {
			return x.Step
		}
	}
	return nil
}

func (x *RunResponse) GetAsk() *Ask {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_Ask); ok {
			return x.Ask
		}
	}
	return nil
}

func (x *RunResponse) GetDone() *Done {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *RunResponse) GetNeedsAcknowledgement() *NeedsAcknowledgement {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_NeedsAcknowledgement); ok {
			return x.NeedsAcknowledgement
		}
	}
	return nil
}

type isRunResponse_Event interface {
	isRunResponse_Event()
}

type RunResponse_Queued struct {
	Queued *Queued `protobuf:"bytes,1,opt,name=queued,proto3,oneof"`
}

type RunResponse_Step struct {
	Step *Step `protobuf:"bytes,2,opt,name=step,proto3,oneof"`
}

type RunResponse_Ask struct {
	Ask *Ask `protobuf:"bytes,3,opt,name=ask,proto3,oneof"`
}

type RunResponse_Done struct {
	Done *Done `protobuf:"bytes,4,opt,name=done,proto3,oneof"`
}

type RunResponse_NeedsAcknowledgement struct {
	NeedsAcknowledgement *NeedsAcknowledgement `protobuf:"bytes,5,opt,name=needs_acknowledgement,json=needsAcknowledgement,proto3,oneof"`
}

func (*RunResponse_Queued) isRunResponse_Event() {}

func (*RunResponse_Step) isRunResponse_Event() {}

func (*RunResponse_Ask) isRunResponse_Event() {}

func (*RunResponse_Done) isRunResponse_Event() {}

func (*RunResponse_NeedsAcknowledgement) isRunResponse_Event() {}

type Queued struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ahead         int32                  `protobuf:"varint,1,opt,name=ahead,proto3" json:"ahead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queued) Reset() {
	*x = Queued{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queued) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queued) ProtoMessage() {}

func (x *Queued) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queued.ProtoReflect.Descriptor instead.
func (*Queued) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{5}
}

func (x *Queued) GetAhead() int32 {
	if x != nil {
		return x.Ahead
	}
	return 0
}

type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{6}
}

func (x *Step) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *Step) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *Step) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Step) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Ask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ask) Reset() {
	*x = Ask{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ask) ProtoMessage() {}

func (x *Ask) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ask.ProtoReflect.Descriptor instead.
func (*Ask) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{7}
}

func (x *Ask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ask) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *Ask) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Ask) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateJson     string                 `protobuf:"bytes,1,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{8}
}

func (x *Done) GetStateJson() string {
	if x != nil {
		return x.StateJson
	}
	return ""
}

type NeedsAcknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []string               `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Discloses     []string               `protobuf:"bytes,2,rep,name=discloses,proto3" json:"discloses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedsAcknowledgement) Reset() {
	*x = NeedsAcknowledgement{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedsAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedsAcknowledgement) ProtoMessage() {}

func (x *NeedsAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedsAcknowledgement.ProtoReflect.Descriptor instead.
func (*NeedsAcknowledgement) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{9}
}

func (x *NeedsAcknowledgement) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NeedsAcknowledgement) GetDiscloses() []string {
	if x != nil {
		return x.Discloses
	}
	return nil
}

type AnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Allow         bool                   `protobuf:"varint,2,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerRequest) Reset() {
	*x = AnswerRequest{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequest) ProtoMessage() {}

func (x *AnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{10}
}

func (x *AnswerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnswerRequest) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

type AnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerResponse) Reset() {
	*x = AnswerResponse{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerResponse) ProtoMessage() {}

func (x *AnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerResponse.ProtoReflect.Descriptor instead.
func (*AnswerResponse) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{11}
}

type AcknowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeRequest) Reset() {
	*x = AcknowledgeRequest{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeRequest) ProtoMessage() {}

func (x *AcknowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeRequest) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{12}
}

func (x *AcknowledgeRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type AcknowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeResponse) Reset() {
	*x = AcknowledgeResponse{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeResponse) ProtoMessage() {}

func (x *AcknowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeResponse) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{13}
}

type DocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "record" reads a record path through docs.get; "file" reads a path
	// relative to the configured files root.
	Source        string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Path          string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentRequest) Reset() {
	*x = DocumentRequest{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentRequest) ProtoMessage() {}

func (x *DocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentRequest.ProtoReflect.Descriptor instead.
func (*DocumentRequest) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{14}
}

func (x *DocumentRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DocumentRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentResponse) Reset() {
	*x = DocumentResponse{}
	mi := &file_atlas_web_v1_ui_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentResponse) ProtoMessage() {}

func (x *DocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atlas_web_v1_ui_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentResponse.ProtoReflect.Descriptor instead.
func (*DocumentResponse) Descriptor() ([]byte, []int) {
	return file_atlas_web_v1_ui_proto_rawDescGZIP(), []int{15}
}

func (x *DocumentResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *DocumentResponse) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *DocumentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_atlas_web_v1_ui_proto protoreflect.FileDescriptor

const file_atlas_web_v1_ui_proto_rawDesc = "" +
	"\n" +
	"\x15atlas/web/v1/ui.proto\x12\fatlas.web.v1\"\x0e\n" +
	"\fViewsRequest\"\x83\x01\n" +
	"\rViewsResponse\x12\x1d\n" +
	"\n" +
	"views_json\x18\x01 \x01(\tR\tviewsJson\x12.\n" +
	"\x06egress\x18\x02 \x03(\v2\x16.atlas.web.v1.EndpointR\x06egress\x12#\n" +
	"\rfiles_enabled\x18\x03 \x01(\bR\ffilesEnabled\"x\n" +
	"\bEndpoint\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06hosted\x18\x02 \x01(\bR\x06hosted\x12\x14\n" +
	"\x05tools\x18\x03 \x03(\tR\x05tools\x12\"\n" +
	"\facknowledged\x18\x04 \x01(\bR\facknowledged\"\xc2\x02\n" +
	"\n" +
	"RunRequest\x12\x12\n" +
	"\x04view\x18\x01 \x01(\tR\x04view\x12\x16\n" +
	"\x06screen\x18\x02 \x01(\tR\x06screen\x12\x16\n" +
	"\x06action\x18\x03 \x01(\x05R\x06action\x12<\n" +
	"\x06params\x18\x04 \x03(\v2$.atlas.web.v1.RunRequest.ParamsEntryR\x06params\x12<\n" +
	"\x06inputs\x18\x05 \x03(\v2$.atlas.web.v1.RunRequest.InputsEntryR\x06inputs\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9c\x02\n" +
	"\vRunResponse\x12.\n" +
	"\x06queued\x18\x01 \x01(\v2\x14.atlas.web.v1.QueuedH\x00R\x06queued\x12(\n" +
	"\x04step\x18\x02 \x01(\v2\x12.atlas.web.v1.StepH\x00R\x04step\x12%\n" +
	"\x03ask\x18\x03 \x01(\v2\x11.atlas.web.v1.AskH\x00R\x03ask\x12(\n" +
	"\x04done\x18\x04 \x01(\v2\x12.atlas.web.v1.DoneH\x00R\x04done\x12Y\n" +
	"\x15needs_acknowledgement\x18\x05 \x01(\v2\".atlas.web.v1.NeedsAcknowledgementH\x00R\x14needsAcknowledgementB\a\n" +
	"\x05event\"\x1e\n" +
	"\x06Queued\x12\x14\n" +
	"\x05ahead\x18\x01 \x01(\x05R\x05ahead\"a\n" +
	"\x04Step\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"`\n" +
	"\x03Ask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\"%\n" +
	"\x04Done\x12\x1d\n" +
	"\n" +
	"state_json\x18\x01 \x01(\tR\tstateJson\"R\n" +
	"\x14NeedsAcknowledgement\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\x12\x1c\n" +
	"\tdiscloses\x18\x02 \x03(\tR\tdiscloses\"5\n" +
	"\rAnswerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05allow\x18\x02 \x01(\bR\x05allow\"\x10\n" +
	"\x0eAnswerResponse\"0\n" +
	"\x12AcknowledgeRequest\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"\x15\n" +
	"\x13AcknowledgeResponse\"=\n" +
	"\x0fDocumentRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"Y\n" +
	"\x10DocumentResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name2\xef\x02\n" +
	"\tUIService\x12@\n" +
	"\x05Views\x12\x1a.atlas.web.v1.ViewsRequest\x1a\x1b.atlas.web.v1.ViewsResponse\x12<\n" +
	"\x03Run\x12\x18.atlas.web.v1.RunRequest\x1a\x19.atlas.web.v1.RunResponse0\x01\x12C\n" +
	"\x06Answer\x12\x1b.atlas.web.v1.AnswerRequest\x1a\x1c.atlas.web.v1.AnswerResponse\x12R\n" +
	"\vAcknowledge\x12 .atlas.web.v1.AcknowledgeRequest\x1a!.atlas.web.v1.AcknowledgeResponse\x12I\n" +
	"\bDocument\x12\x1d.atlas.web.v1.DocumentRequest\x1a\x1e.atlas.web.v1.DocumentResponseBBZ@github.com/tunedev/atlas/internal/adapters/inbound/web/uiv1;uiv1b\x06proto3"

var (
	file_atlas_web_v1_ui_proto_rawDescOnce sync.Once
	file_atlas_web_v1_ui_proto_rawDescData []byte
)

func file_atlas_web_v1_ui_proto_rawDescGZIP() []byte {
	file_atlas_web_v1_ui_proto_rawDescOnce.Do(func() {
		file_atlas_web_v1_ui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atlas_web_v1_ui_proto_rawDesc), len(file_atlas_web_v1_ui_proto_rawDesc)))
	})
	return file_atlas_web_v1_ui_proto_rawDescData
}

var file_atlas_web_v1_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_atlas_web_v1_ui_proto_goTypes = []any{
	(*ViewsRequest)(nil),         // 0: atlas.web.v1.ViewsRequest
	(*ViewsResponse)(nil),        // 1: atlas.web.v1.ViewsResponse
	(*Endpoint)(nil),             // 2: atlas.web.v1.Endpoint
	(*RunRequest)(nil),           // 3: atlas.web.v1.RunRequest
	(*RunResponse)(nil),          // 4: atlas.web.v1.RunResponse
	(*Queued)(nil),               // 5: atlas.web.v1.Queued
	(*Step)(nil),                 // 6: atlas.web.v1.Step
	(*Ask)(nil),                  // 7: atlas.web.v1.Ask
	(*Done)(nil),                 // 8: atlas.web.v1.Done
	(*NeedsAcknowledgement)(nil), // 9: atlas.web.v1.NeedsAcknowledgement
	(*AnswerRequest)(nil),        // 10: atlas.web.v1.AnswerRequest
	(*AnswerResponse)(nil),       // 11: atlas.web.v1.AnswerResponse
	(*AcknowledgeRequest)(nil),   // 12: atlas.web.v1.AcknowledgeRequest
	(*AcknowledgeResponse)(nil),  // 13: atlas.web.v1.AcknowledgeResponse
	(*DocumentRequest)(nil),      // 14: atlas.web.v1.DocumentRequest
	(*DocumentResponse)(nil),     // 15: atlas.web.v1.DocumentResponse
	nil,                          // 16: atlas.web.v1.RunRequest.ParamsEntry
	nil,                          // 17: atlas.web.v1.RunRequest.InputsEntry
}
var file_atlas_web_v1_ui_proto_depIdxs = []int32{
	2,  // 0: atlas.web.v1.ViewsResponse.egress:type_name -> atlas.web.v1.Endpoint
	16, // 1: atlas.web.v1.RunRequest.params:type_name -> atlas.web.v1.RunRequest.ParamsEntry
	17, // 2: atlas.web.v1.RunRequest.inputs:type_name -> atlas.web.v1.RunRequest.InputsEntry
	5,  // 3: atlas.web.v1.RunResponse.queued:type_name -> atlas.web.v1.Queued
	6,  // 4: atlas.web.v1.RunResponse.step:type_name -> atlas.web.v1.Step
	7,  // 5: atlas.web.v1.RunResponse.ask:type_name -> atlas.web.v1.Ask
	8,  // 6: atlas.web.v1.RunResponse.done:type_name -> atlas.web.v1.Done
	9,  // 7: atlas.web.v1.RunResponse.needs_acknowledgement:type_name -> atlas.web.v1.NeedsAcknowledgement
	0,  // 8: atlas.web.v1.UIService.Views:input_type -> atlas.web.v1.ViewsRequest
	3,  // 9: atlas.web.v1.UIService.Run:input_type -> atlas.web.v1.RunRequest
	10, // 10: atlas.web.v1.UIService.Answer:input_type -> atlas.web.v1.AnswerRequest
	12, // 11: atlas.web.v1.UIService.Acknowledge:input_type -> atlas.web.v1.AcknowledgeRequest
	14, // 12: atlas.web.v1.UIService.Document:input_type -> atlas.web.v1.DocumentRequest
	1,  // 13: atlas.web.v1.UIService.Views:output_type -> atlas.web.v1.ViewsResponse
	4,  // 14: atlas.web.v1.UIService.Run:output_type -> atlas.web.v1.RunResponse
	11, // 15: atlas.web.v1.UIService.Answer:output_type -> atlas.web.v1.AnswerResponse
	13, // 16: atlas.web.v1.UIService.Acknowledge:output_type -> atlas.web.v1.AcknowledgeResponse
	15, // 17: atlas.web.v1.UIService.Document:output_type -> atlas.web.v1.DocumentResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_atlas_web_v1_ui_proto_init() }
func file_atlas_web_v1_ui_proto_init() {
	if File_atlas_web_v1_ui_proto != nil {
		return
	}
	file_atlas_web_v1_ui_proto_msgTypes[4].OneofWrappers = []any{
		(*RunResponse_Queued)(nil),
		(*RunResponse_Step)(nil),
		(*RunResponse_Ask)(nil),
		(*RunResponse_Done)(nil),
		(*RunResponse_NeedsAcknowledgement)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atlas_web_v1_ui_proto_rawDesc), len(file_atlas_web_v1_ui_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_atlas_web_v1_ui_proto_goTypes,
		DependencyIndexes: file_atlas_web_v1_ui_proto_depIdxs,
		MessageInfos:      file_atlas_web_v1_ui_proto_msgTypes,
	}.Build()
	File_atlas_web_v1_ui_proto = out.File
	file_atlas_web_v1_ui_proto_goTypes = nil
	file_atlas_web_v1_ui_proto_depIdxs = nil
}
